apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  type: LoadBalancer
  selector:
    app: tasks
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
  labels:
    app: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: starlightromero/kub-network-tasks:latest
          env:
            - name: TASKS_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder
          volumeMounts:
            - mountPath: /app/tasks
              name: tasks-volume
      volumes:
        - name: tasks-volume
          persistentVolumeClaim:
            claimName: tasks-pvc
